#!/bin/bash

# Just to give some time for all subsystems to load
sleep 10

# Run load balancer for BOINC
/home/siriak/repos/useful-scripts/boinc-load-balancer/boinc-load-balancer &

# Pull latest changes for all repositories
/home/siriak/repos/useful-scripts/update-repos &

# Run apps at startup
telegram-desktop &
google-chrome &
transmission-gtk --minimized &
thunderbird &
teams &
zoom &
skype &
slack &
discord &

# Run screenshot tools
python3 /home/siriak/repos/useful-scripts/clipboard-image-saver/clipboard-image-saver.py &
/home/siriak/repos/useful-scripts/timesnapper-for-linux/timesnapper &

