#!/bin/bash

# Just to give some time for all subsystems to load
sleep 10

# Run load balancer for BOINC
/home/siriak/Repos/useful-scripts/boinc-load-balancer/boinc-load-balancer &

# Pull latest changes for all repositories
/home/siriak/Repos/useful-scripts/update-repos &

# Run apps at startup
telegram-desktop &
google-chrome &
transmission-gtk --minimized &
thunderbird &
gnome-pomodoro &

# Run screenshot tool
python3 /home/siriak/Repos/useful-scripts/clipboard-image-saver/clipboard-image-saver.py &

